import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import dev from "../public/dev.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jaime D. Rodriguez Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl dark:text-gray-200">Developed By Jaime</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-gray-200"
                />
              </li>

              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                  download
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Jaime D. Rodriguez
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-200">
              Software Engineer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-200">
              Hi there! welcome to my website. I enjoy developing web solutions
              that help individuals and companies address challenges and
              streamline processes. When I'm not coding, you can find me
              training for long distance races, hiking, reading, or exploring
              the latest technologies.
            </p>
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a
              href="https://twitter.com/your_username"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillTwitterCircle />
            </a>
            <a
              href="https://www.linkedin.com/in/jaime-d-rodriguez"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillLinkedin />
            </a>
            <a
              href="https://github.com/JDRGit"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillGithub />
            </a>
          </div>

          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={dev} layout="fill" objectFit="scale-down" />
          </div>
        </section>
        <section>
          <div className="flex flex-col justify-center text-justify">
            <h3 className="text-3xl py-1 dark:text-white">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I am a Full Stack React Developer, having completed an intensive
              15-week remote technical training program at Per Scholas from
              November 2022 to March 2023. Throughout the course, I gained
              hands-on experience in web development, software engineering, and
              React development, which helped me build a progressive portfolio.
               I have a strong
              understanding of JavaScript and Computer Science concepts,
              including object-oriented programming, Git, advanced HTML/CSS, and
              Redux. I've built Single Page Applications and web applications
              using React, gaining familiarity with client-side routing, AJAX,
              Fetch, and the Context API.
              My full stack
              development experience extends to Java and the Spring Boot
              framework, enabling me to create full CRUD applications, implement
              token-based authentication, and work with REST. I pride myself on
              my excellent problem-solving skills and ability to think like a
              software engineer. I'm now eager to apply my expertise to new job
              opportunities in the software development field.
            </p>
          </div>

          <div className="lg:flex gap-10">
            <div className="flex flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={design} width={100} height={100} alt="Design icon" />
              <h3 className="text-lg font-medium pt-8 pb-2">Frontend Tools</h3>
              <p className="py-2">
                Essential libraries and frameworks for building and styling
                responsive, dynamic, and user-friendly React user interfaces.
              </p>
              <h4 className="py-4 text-teal-600">Some Tools I use</h4>
              <p className="text-gray-800 py-1">Visual Studio Code</p>
              <p className="text-gray-800 py-1">Styled-components</p>
              <p className="text-gray-800 py-1">Material-UI</p>
            </div>

            <div className="flex flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={code} width={100} height={100} alt="Code icon" />
              <h3 className="text-lg font-medium pt-8 pb-2">Backend Tools</h3>
              <p className="py-2">
                Key technologies for creating scalable and efficient server-side
                components, APIs, and databases to power full-stack React
                applications.
              </p>
              <h4 className="py-4 text-teal-600">Development tools I use</h4>
              <p className="text-gray-800 py-1">Node.js</p>
              <p className="text-gray-800 py-1">MySQL</p>
              <p className="text-gray-800 py-1">Express.js</p>
            </div>

            <div className="flex flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                src={consulting}
                width={100}
                height={100}
                alt="Consulting icon"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">Laugages</h3>
              <p className="py-2">
                A collection of helpful tools and platforms for version control,
                code quality, package management, and development workflow
                optimization in full-stack React projects.
              </p>
              <h4 className="py-4 text-teal-600">
                Consulting services I provide
              </h4>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">Java</p>
            </div>
          </div>
        </section>

        <section>
          <div className="py-10 text-justify">
            <h3 className="text-3xl py-1  dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Below is a selection of projects I've worked on during my 15 weeks
              of training, showcasing my skills and growth as a software
              engineer: Currently under construction. Thank you for taking the
              time to explore my portfolio. I'm looking forward to taking the
              next steps in my software development journey and making a
              positive impact in the industry!
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <p>In Progress</p>
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <p>In Progress</p>
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <p>In Progress</p>
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>

        <section>
          <div className="bg-white p-8 rounded-lg shadow-md dark:bg-gray-800">
            <h3 className="text-3xl py-1 dark:text-white">Contact Me (under construction)</h3>
            <form className="mt-4">
              <label
                htmlFor="name"
                className="block text-gray-700 dark:text-gray-200"
              >
                Name
              </label>
              <input
                type="text"
                id="name"
                placeholder="Your Name"
                className="w-full p-2 mt-2 rounded-md border border-gray-300 dark:border-gray-500 dark:bg-gray-700 dark:text-white"
              />

              <label
                htmlFor="email"
                className="block mt-4 text-gray-700 dark:text-gray-200"
              >
                Email
              </label>
              <input
                type="email"
                id="email"
                placeholder="Your Email"
                className="w-full p-2 mt-2 rounded-md border border-gray-300 dark:border-gray-500 dark:bg-gray-700 dark:text-white"
              />

              <label
                htmlFor="message"
                className="block mt-4 text-gray-700 dark:text-gray-200"
              >
                Message
              </label>
              <textarea
                id="message"
                placeholder="Your Message"
                rows="6"
                className="w-full p-2 mt-2 rounded-md border border-gray-300 dark:border-gray-500 dark:bg-gray-700 dark:text-white"
              />

              <button
                type="submit"
                className="mt-6 bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md"
              >
                Send Message
              </button>
            </form>
          </div>
        </section>
      </main>
    </div>
  );
}
